# Generated by Django 4.1.4 on 2022-12-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("save_country", "0002_rename_country_country_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="TotalConfirmed",
            field=models.TextField(max_length=56),
        ),
        migrations.AlterField(
            model_name="country",
            name="TotalDeaths",
            field=models.TextField(max_length=56),
        ),
        migrations.AlterField(
            model_name="country",
            name="TotalRecovered",
            field=models.TextField(max_length=56),
        ),
    ]
